version: '3.7'

services:
  ner:
    build:
        context: ./services/ner-service
        dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - ./data/ner-service:/ner_service/data
    expose:
      - "18861"
  web:
    build:
        context: ./services/web
        dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./data/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - ner
      - redis
  worker:
    build:
      context: ./services/celery-queue
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
     - "5555:5555"
    volumes:
      - ./data/celery-flower:/persistent
    depends_on:
      - ner
      - redis
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  celery-flower_data:
